import { LaunchScreen }       from './launch';
import { TermsAndConditions } from './terms-conditions';
import { PrivacyPolicy }      from './privacy-policy';

import { 
    DebitCardPage,
    AccountSettings,
    Home,
    Notifications,
    UpdateUserData,
    AddDebitCard,
    BankDataPage,
    KYCPage,
    KYCMeansOfID,
    KYCRegionSelection,
    KYCAddressPage,
    FundWallet,
    AddBankAccount,
    ChoosePayment,
    WithdrawalSettings,
    TransactionsPage,
    TransactionDetails,
    ReferralPage,
    PerformancePage,
    PerformanceOrdersList,
    PerformanceOrderDetails,
    NextOfKin,
    UMAgentIdentityCheck,
    UMAgentRegionSelection,
    UMAgentBankAccount,
    UMAgentGroup,
    KYCAgentBankData,
    SuccessPage,
    AccountVerified,
    WalletToWallet,
    AgencyBankingSignup
} from './home';

import {
    PhoneNumberSignUp,
    ChooseRole,
    Check,
    Login,
    MerchantSignUp, 
    MerchantCreatePin, 
    MerchantBusinessProfile,
    AgentProfileCreation,
    AgentIdentityCheck,
    AgentRegionSelection,
    AgentBankAccount,
    AgentGroup,
    AgentPinCreation,
    ForgotPassword,
    SetNewPassword,
    UpdatePassword,
    OTPVALIDATION403
} from './auth';


export {
    LaunchScreen,
    ChooseRole,
    PhoneNumberSignUp,
    MerchantSignUp, 
    MerchantCreatePin, 
    MerchantBusinessProfile,
    AgentProfileCreation,
    AgentIdentityCheck,
    AgentRegionSelection,
    AgentGroup,
    AgentBankAccount,
    AgentPinCreation,
    Check,
    Login,
    ForgotPassword,
    SetNewPassword,
    UpdatePassword,
    Home,
    Notifications,
    NextOfKin,
    DebitCardPage,
    BankDataPage,
    AddDebitCard,
    AddBankAccount,
    FundWallet,
    WithdrawalSettings,
    ChoosePayment,
    AccountSettings,
    KYCPage,
    KYCMeansOfID,
    KYCRegionSelection,
    KYCAddressPage,
    ReferralPage,
    TransactionsPage,
    TransactionDetails,
    PerformancePage,
    PerformanceOrdersList,
    PerformanceOrderDetails,
    UpdateUserData,
    TermsAndConditions,
    PrivacyPolicy,
    UMAgentIdentityCheck,
    UMAgentRegionSelection,
    UMAgentBankAccount,
    UMAgentGroup,
    KYCAgentBankData,
    OTPVALIDATION403,
    SuccessPage,
    AccountVerified,
    WalletToWallet,
    AgencyBankingSignup
};