export const LOADING                             = 'LOADING';
export const PROCESSING_ORDER                    = 'PROCESSING_ORDER';
export const FETCH_RECOMMENDED_PRODUCTS_SUCCESS  = 'FETCH_RECOMMENDED_PRODUCTS_SUCCESS';
export const FETCH_RECOMMENDED_PRODUCTS_FAILURE  = 'FETCH_RECOMMENDED_PRODUCTS_FAILURE';
export const FETCH_POPULAR_PRODUCTS_SUCCESS      = 'FETCH_POPULAR_PRODUCTS_SUCCESS';
export const FETCH_POPULAR_PRODUCTS_FAILURE      = 'FETCH_POPULAR_PRODUCTS_FAILURE';
export const FETCH_ALL_PRODUCTS_SUCCESS          = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAILURE          = 'FETCH_ALL_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_CATEGORIES_SUCCESS   = 'FETCH_PRODUCTS_CATEGORIES_SUCCESS';
export const FETCH_PRODUCTS_CATEGORIES_FAILURE   = 'FETCH_PRODUCTS_CATEGORIES_FAILURE';
export const FETCH_PRODUCTS_BY_SHOP_ID_SUCCESS   = 'FETCH_PRODUCTS_BY_SHOP_ID_SUCCESS';
export const FETCH_PRODUCTS_BY_SHOP_ID_FAILURE   = 'FETCH_PRODUCTS_BY_SHOP_ID_FAILURE';
export const FETCH_SHOPS_SUCCESS                 = 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAILURE                 = 'FETCH_SHOPS_FAILURE';
export const FETCH_SHOP_BY_ID_SUCCESS            = 'FETCH_SHOP_BY_ID_SUCCESS';
export const FETCH_SHOP_BY_ID_FAILURE            = 'FETCH_SHOP_BY_ID_FAILURE';
export const FETCH_PRODUCT_BY_ID_SUCCESS         = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE         = 'FETCH_PRODUCT_BY_ID_FAILURE ';
export const FETCH_AVAILABLE_STATES_SUCCESS      = ' FETCH_AVAILABLE_STATES_SUCCESS';
export const FETCH_AVAILABLE_STATES_FAILURE      = ' FETCH_AVAILABLE_STATES_FAILURE ';
export const FETCH_SHOP_CART                     = 'FETCH_SHOP_CART';
export const FETCH_SHIPPING_OPTIONS              = 'FETCH_SHIPPING_OPTIONS';
export const SAVE_LAST_ORDER_PLACED              = 'SAVE_LAST_ORDER_PLACED';
export const SERVICE_CHARGE_PERCENT              = 'SERVICE_CHARGE_PERCENT';
export const MERCHBUY_DELIVERY_LOCATION          = 'MERCHBUY_DELIVERY_LOCATION';
export const SET_CHOSEN_ORDER_HISTORY            = 'SET_CHOSEN_ORDER_HISTORY';
export const FETCH_CHOSEN_ORDER_HISTORY_FAILURE  = 'FETCH_CHOSEN_ORDER_HISTORY_FAILURE';
export const CLEAR_CHOSEN_ORDER_HISTORY          = 'CLEAR_CHOSEN_ORDER_HISTORY'
export const MERCHBUY_ORDER_HISTORY_SUCCESS      = 'MERCHBUY_ORDER_HISTORY_SUCCESS'; 
export const MERCHBUY_ORDER_HISTORY_FAILURE      = 'MERCHBUY_ORDER_HISTORY_FAILURE'; 




